mvdan/sh

parse.go
Thanks for cool library and  tool!
I develop a linter for dockerfile by golang. https://github.com/pocke/dflint
In this tool, I use this library as a shell parser.
I've implemented a feature to detect syntax errors of shell. 
However, `lineErr` is not exported. So, I haven't implemented displaying positions of error yet.
I propose to expose `lineErr`.
=> Expose LineErr

.travis.yml, cmd/shfmt/main.go
I'm working on getting `shfmt` added to the default preinstalled stuff on the Travis CI VMs, and I'd like to be able to include the `shfmt` version in the VM metadata.  I realize that having a hardcoded version is a bit of a pain, and I'd typically implement this as an injected string of `git describe --always --tags` or similar, but didn't want to introduce such a big change without first proposing the flag.
=> Add -version flag for reporting version

interp/interp_test.go, syntax/parser_test.go
Closes #89
---
Seems that Ubuntu use `LANGUAGE` instead of `LC_ALL`.
=> Fix locale issue on tests

cmd/shfmt/json.go
Don't recurse into nil interfaces.
```
$ echo "FOO=a" | shfmt -exp.tojson
panic: reflect: call of reflect.Value.Interface on zero Value
goroutine 1 [running]:
reflect.valueInterface(0x0, ext:0x0, 0x0, 0x1, 0xc4200451d8, 0x40e142)
/usr/lib/go/src/reflect/value.go:930 +0x1fa
reflect.Value.Interface(0x0, ext:0x0, 0x0, 0xc420092500, 0x280)
/usr/lib/go/src/reflect/value.go:925 +0x44
main.recurse(0x0, ext:0x0, 0x0, 0x0, 0x0, 0x0, 0x7faf80805960)
[...]/go/src/github.com/mvdan/sh/cmd/shfmt/json.go:75 +0x485
[..]
```
=> cmd/shfmt: fix panic on Stmts without Command in -exp.tojson

interp/dev.go, interp/interp.go, interp/interp_test.go
This fix reading and writing to /dev/null on Windows, where this file is not available.
It may also add a very minimal performance improvement on other plataforms, since now interp don't need to open and redirect to a real file anymore.
Reference: #141 
---
@mvdan Consider this a proposal, and feel free to reject it if you decide against it, or have a better idea about how to implement this.
=> interp: have a custom /dev/null implementation

.travis.yml, interp/builtin.go, interp/interp_test.go, interp/perm_other.go, interp/perm_win.go
This commit reintroduces bc1c6f7cf372d921cb3594b2d23a2cab08d5fd23, but with build tags to fix build on Windows.
Closes #148
=> interp: cd now checks for exec permissions

interp/interp_test.go
bash prints the pwd after changing directories when CDPATH is set, which
made some of the TestFileConfirm tests fail.
=> interp: unset CDPATH during tests.

interp/interp.go, interp/interp_test.go
```
printf "%%\n"      
printf "%"
printf "%02d\n" 1 
```
bash
```
%
x.sh: line 2: printf: `%': missing format character
01
```
gosh (before)
```
x.sh:0:0: unhandled format char: %
2d
x.sh:0:0: unhandled format char: 0
```
gosh (after)
```
%
x.sh:0:0: missing format char
x.sh:0:0: unhandled format char: 0
```
=> interp: printf %% and error handling

interp/interp.go, interp/interp_test.go
The idea is to let the fmt package do the heavy lifting and just translate the
format char/arg type as required. There might be hidden gotchas I've not yet
discovered, but it seems to work as expected so far.
=> interp: handle more printf formats

interp/interp.go, interp/interp_test.go, interp/test.go
Also never export arrays.
This is what I used for testing:
```
unset X A AA
X=0
A=(a b c)
declare -A AA=([foo]=bar)
set -a
X=1
A[0]=A
AA[foo]=rab
echo $X $A ${AA[foo]}
/bin/sh -c 'echo $X $A ${AA[foo]}'
X=(a b c)
echo $X
echo ${X[1]}
/bin/sh -c 'echo $X'
```
bash
```
1 A rab
1
a
b
```
gosh
```
1 A rab
1
a
b
```
Not sure how to translate this into a proper testcase.
=> interp: support set -a

interp/builtin.go, interp/interp.go, interp/interp_test.go
This makes Runner.expand return the number of arguments actually consumed by
the format. printf then just iterates r.expand until all arguments are consumed
(given it consumes arguments at all).
```
printf "%d" 1 2 3
```
bash: `123`
gosh (before): `1`
gosh (after): `123`
=> interp: support printf %d 1 2 3

interp/builtin.go, interp/interp_test.go
Previously read was able to create variables with invalid names. Check
that the names are valid identifiers before doing anything and error if
they are not. Also add a missing reslice in ifsFields().
=> interp: reject invalid identifiers in the read builtin

interp/builtin.go, interp/interp.go, interp/interp_test.go
Initial attempt at the getopts builtin. Tracking state across multiple getopts
invocations is a bit ugly (necessary for -abc shortcuts) and so is detecting
intervening assignments to OPTIND. State split into a separate getopts struct in
the hope it could be used to handle options to the builtins too.
=> interp: support getopts

interp/builtin.go, interp/interp_test.go
Like in the read builtin, make sure we don't create variables with invalid
identifiers. Also fix/improve read/popd error messages.
=> interp: reject invalid identifiers in getopts

cmd/shfmt/main.go
If a file is only readable but not writeable and does not
contain a valid shebang shfmt should not fail.
This implementation always opens the file twice.
These two additional syscalls seem negligible compared to
the added complexity to only open it twice if the write flag
is set.
Fixes #207
=> Open file read-only to check for shebang

syntax/example_walk_test.go, syntax/walk.go
A simpler, smaller version of ast.Fprint but for our AST. Include an
example too, which also serves as its test.
Field filtering is left out, as it seems like an overkill feature for
what is essentially a debugging function.
The reflect code isn't very complex, as our AST doesn't contain certain
types like maps and arrays, nor do any node structs contain unexported
fields.
=> syntax: add DebugPrint

cmd/shfmt/main.go, syntax/printer.go, syntax/printer_test.go
That is, to format them like:
echo foo > file
This format is somewhat popular in the wild, and it is mentioned in some
prominent documents like 'man bash' and Classic Shell Scripting.
The option is very specific and doesn't clash with any other existing
options, so it shouldn't complicate the printer in the long run.
The Google Shell Style guide doesn't explicitly say how to format
redirections, so for now don't change its recommendation on the main
README file.
Don't change the default, as that would break backwards compatibility.
It's also not clear that this new format is vastly more popular than the
current one. For example, the POSIX Shell spec doesn't use spaces, and
the shfmt tool didn't have support for them.
Fixes #243.
=> syntax: add an option to space redirect ops

interp/builtin.go, interp/interp.go
Every range over array that binds a value does a full copy of array being iterated.
The workaround is to either use `&x` instead `x` or do index-only range.
In this case, shellOptsTable (192 bytes) is copied before each changed range stmt.
Not it does only pointer copy. Compiler optimizes accesses, so there is no
drawbacks for this. (And there is close to no difference for sizes of < 48 byte.)
See: https://github.com/cristaloleg/go-advices
=> interp: avoid redundant array copies

interp/module.go, interp/param.go, syntax/walk.go
Usually makes code simpler.
There are no TODO notes, so I've treated
these switches as refactoring artifacts.
=> interp,syntax: replace single case switches

syntax/lexer.go, syntax/printer.go
Usually this form is considered more idiomatic.
I've left if-else chains with init statements untouched
to less obvious changes.
Found with `elseif` check from go-critic linter.
=> syntax: replace if-else chains with expr switch stmt

interp/builtin.go, interp/interp.go, interp/interp_test.go, interp/test.go
=, != behaved the same whether inside `[` or `[[`. Distinguish the two
in Runner.bashTest as `[` should not do pattern matching when matching
strings.
Fixes #271
=> interp: fix classic test string matching

README.md
This helps improve readability in README.md :smile:
=> README: Enable sh syntax highlight in code blocks

README.md
This Docker repository releases with corresponding upstream version tag, updates more frequently, and also brings basic shell utils provided `busybox` which could be helpful, especially for those Docker native CI environment like GitLab CI (So that we don't need to override the entrypoint).
=> README: Add another Dockerized shfmt / Docker repo

interp/vars.go
This was causing issues on windows where the child process would start with 32 empty items and on windows the process would not get all the environment variables.
You can see the issue running
`gosh -c "cmd /C set"`
and on mac this print a bunch of white space before the variables
`gosh -c "env"`
=> Setting the initial capacity of the array rather than the length

README.md
`shfmt` also exists as a snap
Source: https://snapcraft.io/shfmt
=> shfmt snap reference added

interp/builtin.go, interp/interp.go, interp/interp_test.go
As correctly pointed out by Marcin Bilski, using the exported function
in that way would lead to a panic. And, even after working around the
panic, any shell flags used would be overwritten by the first implicit
call to Reset.
To fix the crash, move the updateExpandOpts method call to the end of
the "set" builtin. After all, it's only needed there; the Run function
already ends up calling the method later via fillExpandConfig.
To keep the shell options from being deleted in Reset, simply whitelist
them from the list of fields to clear. We do that for Params, so it
follows that the same should happen for the opts field.
Finally, add a couple of tests covering both scenarios to
TestRunnerOpts.
Fixes #365.
=> interp: fix using Params as an option to New

expand/param.go
This commit rewrites if-else-if-else chain as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
=> Rewrite if-else-if-else chain as a switch

cmd/shfmt/main.go, cmd/shfmt/main_test.go
This PR supports color output for the added/deleted lines in diff mode.
Current:
When PR is merged:
=> Support color output for the added/deleted lines in diff mode

interp/module.go
Type aliases are used to refer to types in other packages.
No need for them here.
=> interp: don't use type aliases for functions

cmd/gosh/main.go, cmd/gosh/main_test.go
Func interactive() depends on runner.Std* which will be unexported
in a follow-up PR. To remove that dependency we pass runner and
std* directly to functions instead of using global vars.
=> cmd/gosh: remove usage of global variables

interp/example_test.go, interp/interp.go, interp/interp_test.go, interp/module.go, interp/module_test.go
Middleware style api is overcomplicated for users and require a lot of glue code,
makes path handling unclear on windows and produces weird stack traces.
Switch to simple functions for now. If user wants to compose their handlers,
they can implement whatever interface is comfortable to use for them themselves.
Renames:
WithExecModules -> ExecModule
WithOpenModules -> OpenModule
OpenModule -> OpenModuleFunc
ExecModule -> ExecModuleFunc
Removed OpenDevImpls - it's unclear what signature it should have.
It can be readded later, if needed.
Switched tests and examples to new api.
Fixes #421
Fixes #419
=> interp: use simple funcs instead of middlewares in Open/ExecModule

interp/builtin.go, interp/interp.go
These fields are supposed to be modified via calling options
and there is little reason to read from them.
Fixes #428
=> interp: unexport Open,Exec,Stdin,Stdout,Stderr from Runner

interp/example_test.go, interp/interp.go, interp/interp_test.go, interp/module.go, interp/module_test.go
KillTimeout is specific to DefaultExec,
other exec implementations, like those written in go,
don't benefit from it (you can't kill a goroutine).
Also updated DefaultOpen for consistency.
This also makes Default* functions group under their
respective type in godoc.
Fixes #420.
=> interp: move KillTimeout to DefaultOpen

cmd/gosh/main.go, go.mod, go.sum, interp/builtin.go, interp/example_test.go, interp/handler.go, interp/handler_test.go, interp/interp.go, interp/interp_test.go
Unexport ExitStatus.
Replace with NewExitStatus() and IsExitStatus().
Fixes #426.
=> interp: use functions for exit status checks

.github/workflows/test.yml
Restrict CI test 'fuzz continuous jobs' to original repo user mvdan as poposed in #481.
=> Fix fuzzing failure for forked repos

.github/workflows/test.yml
Similar fix to #482 but for docker deploy stage of Github Actions CI.
Syncing forks should come out green from the CI again now.
=> Fix docker deploy failure for forked repos

expand/expand.go, expand/expand_test.go
Currently only the first run of a syntax tree would expand braces when it splits them,
resulting in the following panic of the new test.
```
=== RUN   TestFields
=== RUN   TestFields/00-run-1
=== RUN   TestFields/00-run-2
panic: unhandled word part: *syntax.BraceExp [recovered]
panic: unhandled word part: *syntax.BraceExp
goroutine 9 [running]:
testing.tRunner.func1(0xc0000d4300)
/usr/lib/go/src/testing/testing.go:874 +0x3a3
panic(0x55f7e0, 0xc000062ec0)
/usr/lib/go/src/runtime/panic.go:679 +0x1b2
mvdan.cc/sh/v3/expand.(*Config).wordFields(0x6ca540, 0xc00000fd20, 0x2, 0x2, 0x0, 0x22, 0xc000000349, 0xc00004ee60, 0x4c43de)
/home/duncan/repos/sh/expand/expand.go:606 +0x1392
mvdan.cc/sh/v3/expand.Fields(0x6ca540, 0xc0000c7f18, 0x1, 0x1, 0x349, 0x4c43b0, 0x6676c8, 0x6b7940, 0xc00009a400) …
```
=> expand: always expand braces

cmd/shfmt/main.go, cmd/shfmt/main_test.go
Ensure that invoking shfmt -f on files yields the same result as when
invoked with the directory containing the files. In other words, the
output of `shfmt -f` should only contain files which have been detected
as shell files. This changes shfmt's behavior whereby previously, given
the following file tree:
bin
├── README.md
└── script.sh
running `shfmt -f bin` would output:
bin/script.sh
but running `shfmt -f bin/script.sh bin/README.md` would output:
bin/script.sh
bin/README.md
As of this commit the output for both cases is consistent.
=> shfmt: fix behavior of -f flag for file arguments

interp/interp.go, interp/interp_test.go
Copy makes a copy of the given Runner, suitable for use in parallel to the original.  The copy will have the same parameters, environment variables, etc, but they can all be modified without affecting the original.
Also fixes a tiny typo in a comment in the definition of Runner ("sub" vs "Sub").
Edit/clarification: This PR started life adding a `Copy` method on `Runner`; only later was it updated to rename `sub` to `Subshell` and fix some bugs in it that `Copy` had fixed.
=> interp: rename sub to Subshell, and fix some bugs

cmd/shfmt/Dockerfile, cmd/shfmt/docker-entrypoint.sh
Docker (the org) likes to have its containers be consistent [0] and by
adding a simple entrypoint script we become compliant. This would in the
future allow it to be possible to become an 'official' container.
In any case, it also makes the application behave as expected from a
users point of view.
e.g. running the container only arguments, invokes shfmt. Adding `shfmt`
as the first argument, also still works as expected.
More importantly, it allows for starting the container with a shell by
using `/bin/sh` as an argument.
The last point is important as it allows CI's such as gitlab to use the
container 'as is' and run shfmt inside of it.
[0] https://github.com/docker-library/official-images#consistency
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
=> cmd/shfmt: Make the docker container consistent

cmd/shfmt/main.go, cmd/shfmt/testdata/scripts/basic.txt
Proposal to treat '-' on the command line as stdin, like it has been done forever by many Unix command line tools.
This came up when I was trying to run the minimal docker image with stdin and needed to override the default docker image command line argument of '-h'. I.e. `cat my.sh | docker run -i --rm shfmt` currently doesn't work since the image executes 'shfmt -h'. One option is to override some command line argument with it's default value, e.g. `cat my.sh | docker run -i --rm shfmt -i 0`. But IMHO a cleaner option would be to support the '-' filename argument, i.e. `cat my.sh | docker -i --rm shfmt -`.
=> Add support for '-' filename to mean stdin

.github/workflows/test.yml
It irked me that moving the docker image build from DockerHub auto-build to Github Actions had lost the automatic update of the info (aka. repository description) on DockerHub's web UI. So this PR puts it back, using the DockerHub API.
=> Add DockerHub description upon deployment

.github/workflows/test.yml
Just polishing the previous PR #492 a bit after seeing that error reporting was not working well.
Now CI will show a failure if the DockerHub login credentials don't work as expected.
=> Improve error reporting from Dockerhub API

interp/builtin.go, interp/handler_test.go
Set runner exitShell to true before calling the exec handler for exec builtin, this way exec handlers could retrieve this information via runner.Exited() and take appropriate actions.
Not sure if this is the best way to handle that but in a first time it would allow to retrieve this information without dealing with statements and parsing to know if it's an exec builtin or a sub-process.
=> Set runner exitShell to true before calling the exec handler for exec builtin

interp/interp.go, interp/interp_test.go
Other environment variables are copied in Runner.SubShell, but $? is special (stored in Runner.exit) and was missed.
This may or may not be behavior explicit in the bash manpage; tbh I haven't checked.  But it is what bash _does_:
```sh
bash-3.2$ false ; ( echo $? )
1
```
=> interp: copy Runner.exit in SubShell

interp/builtin.go, interp/interp_test.go
=> interp: make "type" builtin respect the current $PATH

.github/workflows/test.yml
We want the alpine container to show up as a tag, not as its own repo.
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
Closes #504
=> Push alpine container to the proper repository

cmd/shfmt/main.go, syntax/printer.go, syntax/printer_test.go
Hi,
I have added two new printer options for a less compact style.
`-knl` (_keyword new line_) will put keywords like "then" and "do" on a new line.
**Example:**
```
if foo
then
bar
fi
```
`-bnl` (_brace new line_) will put braces on new lines.
**Example:**
```
foo()
{
bar
}
```
It would be great if you would accept the patch. Let me know if there is anything I need to change.
Regards,
Morgan
=> Add two new printer options: -knl and -bnl

interp/builtin.go, interp/interp.go, interp/interp_test.go
Currently sourced scripts can't changes interpreter parameters, the following script should display `arg1 arg2`:
```
set --
cat > /tmp/source <<EOF
set -- arg1 arg2
EOF
source /tmp/source
echo $@
```
=> Fix an issue not propagating interpreter parameters changes from sourced scripts.

interp/interp.go, interp/interp_test.go
Doing the following should not return a readonly variable error
```
readonly foo=bar
export foo
```
=> Fix issue with readonly and naked export.

README.md
With this, people can easily hook shfmt to their pre-commit checks. More info: https://pre-commit.com/
=> Document pre-commit hook

syntax/parser.go, syntax/parser_arithm.go, syntax/parser_test.go
Here I'm replacing the parser with a recursive-descent parser that's
modeled after the parser used in Bash. All the methods correspond to
methods in Bash's expr.c.
This fixes operator precedence problems like #579
Fixes #579
=> syntax: replace Arithmetic parser with a recursive-descent parser

syntax/parser.go, syntax/parser_test.go
Printing the token where the parser stops can help when debugging why a shell command fails to get parsed, so I'd like to upstream a patch to do so. 
Let me know your thoughts on this.
Thanks,
Hamza
=> syntax: Record token at which parser stops for default case.

cmd/shfmt/main.go
Between the `v2.6.4` and `v3.0.0` there is a regression in the diff output.
Before it was done with the command `diff -u` but now with the package `github.com/pkg/diff` without the [WithContextSize](https://pkg.go.dev/github.com/pkg/diff@v0.0.0-20190915220856-5883b2e1a98f?tab=doc#EditScript.WithContextSize) option output a full diff which is a regression and boring.
I just add a `WithContext(3)` to restore the former behavior.
=> Restore unified diff on -d flag

syntax/printer.go, syntax/printer_test.go
I went through a few scripts that caused me trouble, and with this patch they all seem to behave fine.
Reflected in tests all the gotchas that I stumbled upon, namely my initial example, a simple indented line, comments.
If you can think of more edge cases, please let me know 🙂 
If I find some examples where this logic fails, I will return with another PR 😄 
Fixes #471
=> Preserve indentation on line start with -kp and space indent

README.md
and while `http://mirbsd.de/mksh` “[is the canonical homepage URI” “via a redirection](http://www.mirbsd.org/mksh.htm)”, that address is also pointing to mirbsd.org over HTTPS, which is no longer accessible without disabling secure settings.
cc @mirabilos
=> repair linkrot: mirbsd.org no longer reliably HTTPS-accessible

interp/interp_test.go, interp/vars.go
The interpreter had a bug where the empty expansion is not removed in a
call when a shift operation caused it to become empty. This is due to
shift's behavior of setting interp.Runner.Params to nil when no more
positional parameters are left.
Unfortunately, looking up $@ and $* returns a value with with List set
to interp.Runner.Params, meaning the List field can be nil when the
variable claims to be set. This breaks expand's expectation of List type
existence meaning non-zero values are available, as seen in
`quotedElemFields`.
This changes interp's environment lookup to always return a non-nil
[]string for $@ and $*, satisfying expand's expectations.
Fixes #606.
=> interp: $@ and $* always exist

CHANGELOG.md, syntax/filetests_test.go, syntax/nodes.go, syntax/parser.go, syntax/printer.go, syntax/printer_test.go
Bash supports `foo() {}`, `function foo {}`, and `function foo() {}`.
Currently, shfmt always prints parentheses, i.e. `function foo {}` is always printed as `function foo() {}`.
This patch changes shfmt to only add parentheses, if they were in the original source.
Reasons:
- imo this may be unexpected for some users of Bash
- ksh only supports `foo() {}` and `function foo {}`, but not `function foo() {}`. This patch slightly increases compatibility with this and hopefully allows to run shfmt on more .ksh file (which is useful for [BashSupport Pro](https://www.bashsupport.com))
As this is my first PR for shfmt, this may not match the expectations or requirements :) Please let me know what should be changed or if this isn't how shfmt is supposed to work. Thansk!
=> shfmt: Don't add parentheses to functions, if they were not in the original source

.github/workflows/test.yml
Use the following actions instead of manual Docker buildx setup:
- https://github.com/docker/login-action
- https://github.com/docker/setup-qemu-action
- https://github.com/docker/build-push-action
Notes:
- It would be good to merge "Build and push" and "Build and push
(alpine)" steps but I have no solution to propose for now;
- there are some linting changes (using prettier).
WIP because CI needs to be tested against upstream repo:
- create a DOCKER_USER secret so that forks can test the CI (push);
- I am using token and 2FA on DockerHub so the update description step
could not be tested.
Regarding the last step (Update DockerHub description), we may consider using this https://github.com/marketplace/actions/docker-hub-description.
=> Use official Docker GitHub actions

interp/builtin.go, interp/example_test.go, interp/handler.go
The main motivation is to make the cwd more explicit. Previously it was implied by assuming that a "PWD" environment variable exists.
=> interp: LookPathDir

README.md
Webi can be used to effortlessly install developer tools with easy-to-remember URLs and shfmt has been added to the list of tools that can be installed using webi.
For more info, visit website https://webinstall.dev/shfmt/
or github repo  https://github.com/webinstall/webi-installers/tree/master/shfmt
=> Added webi to install methods

README.md
Hi!
I integrated `shfmt` with the [mdformat](https://github.com/executablebooks/mdformat) Markdown formatter. The idea is that when formatting Markdown, any embedded code blocks tagged with `sh` or `bash` are also formatted with `shfmt`.
I noticed you have a README section for integrations so thought you might be interested in adding this? I understand if there's some criteria (adoption, GitHub stars... ?) for this integrations list that might prevent doing so 😄
=> Add mdformat-shfmt to readme integrations section

interp/interp_test.go, interp/vars.go
Bash array values are generally expanded. For example:
```
$ x=($(echo a b)); echo ${x[0]}
a
```
The exception is when an index is provided. Those values are taken
literally.
```
$ x=([0]=$(echo a b)); echo ${x[0]}
a b
```
The runner expands values in `assignVal` and did so by mapping the
expression index to the array index. A fixed mapping fails when a value
generates more than one field. Hence the code interpreted all array
values as literal.
This change iterates over the elements, expanding literally or with
fields, while keeping track of the implicit index. The result is then
flattened down at the computed indexes.
Fixes #671
=> interp: expand array arguments

interp/interp_test.go, interp/vars.go
Local variables should be mutable but f4c774a accidentally made them
immutable. A new assignment is made with a new `expand.Variable` struct,
which defaults the Local flag to false. Failing to preserve the
localness of an overlayed variable means future sets are incorrectly
forwarded to the global scope.
Fixes #674
=> interp: local vars are mutable

expand/environ.go, expand/environ_test.go
`expand.ListEnviron` does not specify which value is selected when there
are duplicate name=value pairs. The test implied there was last-entry
ordering, but in reality it's lexicographical ordering. This tweaks the
test to better show the as-implemented behavior, even if it's not
guaranteed behavior.
=> expand: expand.ListEnviron prefers last value

syntax/filetests_test.go, syntax/parser.go, syntax/parser_test.go
Per the NEWS:
dd. New `U', `u', and `L' parameter transformations to convert to uppercase,
convert first character to uppercase, and convert to lowercase,
respectively.
hh. New `K' parameter transformation to display associative arrays as key-
value pairs.
=> Add Bash 5.1 parameter transformations

cmd/shfmt/shfmt.1.scd
You need `-bn` to get Google style with shfmt. This commit changes the
man page to reflect that.
Google's shell style guide says long pipelines:
should be split at one pipe segment per line with the pipe on the
newline and a 2 space indent for the next section of the pipe. This
applies to a chain of commands combined using | as well as to
logical compounds using || and &&.
command1 | command2
command1 \
| command2 \
| command3 \
| command4
See https://google.github.io/styleguide/shellguide.html#s5.3-pipelines
=> Add -bn to flags for Google's shell style

interp/api.go, interp/interp_test.go
Set GID environment variable analog to UID.
Rel: https://github.com/go-task/task/issues/561
Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>
=> interp/api: set GID

interp/builtin.go, interp/interp_test.go
I'm new at Go so please point out if I've made any errors; I tried to mimic the style of the other code blocks.
This resolves #724 and [go-task#553](https://github.com/go-task/task/issues/553)
=> Add support for pwd -P

expand/param.go, syntax/example_test.go, syntax/fuzz_test.go, syntax/lexer.go
=> syntax: add a Quote func

expand/param.go, go.mod, go.sum, syntax/example_test.go, syntax/fuzz_test.go, syntax/lexer.go, syntax/parser.go, syntax/quote.go, syntax/quote_test.go, syntax/testdata/fuzz/FuzzQuote/25f36feab4af00bc4dfc3cf56da02b842b62ba8c5ac44862b5b3b776a0d519b4, syntax/testdata/fuzz/FuzzQuote/2788bd30d386289e06a1024a030ad5ab7f363c703bea8a5d035de174491029bf, syntax/testdata/fuzz/FuzzQuote/39d5fdf93d52b2cd50fb9582b27c82d159de0575623865538ced2a7780499fa6, syntax/testdata/fuzz/FuzzQuote/6fcce067200fb8ae6d4c2b1b7c1f55d3f7e4b38f4ee4f05e50e496a7c399f2d8, syntax/testdata/fuzz/FuzzQuote/b26cd471412059c6ab6aa27b6153d42d2d00cbb00ad11d3cd88a192a7dfd2cdf, syntax/testdata/fuzz/FuzzQuote/df6b5d69da50c7d58ca13f6dde15e2a7224a53ce7bd72a02d49893e580b6775b, syntax/testdata/fuzz/FuzzQuote/ea14da9b0299f4463c20659e2a51808fef8d5fb0de6324f0de64153511d4b1f8
=> syntax: add a LangVariant parameter to Quote

expand/param.go, interp/interp_test.go, syntax/parser_test.go
prior to this PR, we slice the elements of `variable.Str` but that's
buggy; the package `expand` expands the bash array `arr=(x y z)`
as `"x y z"`, a string with space between members. when accesing via
indexes, in effect we get `str[2] == "y"`
this PR fixes the bug by making use of the expanded `variable.List`
field instead to access the elements of the bash array
fixes #746
=> interp: fix off-by-one bug when printing arrays

README.md
This adds an example for running shfmt in a local pre-commit hook using the official shfmt docker image for cases where golang is not installed.
=> Add example for docker-based pre-commit hook

interp/interp_test.go, interp/vars.go
Variables declared as exported or readonly in functions
without assignment are not correctly propagated to the
global scope, this snippet should return a `bar: readonly variable`
error:
```
_foo() {
bar=foo
readonly bar
}
_foo
bar=bar
```
This snippet should also export `bar` variable correctly:
```
_foo() {
export bar
}
_foo
bar=foo
env | grep ^bar=
```
=> interp: fix variables scope in functions

README.md
The primary reason for this is to facilitate autoupdating. pre-commit's
`autoupdate` as well as other tooling capable of updating pre-commit
hook configs such as https://github.com/renovatebot/renovate work with
git tag `rev`s. I'm not aware of anything publically available at the
moment that would be able to update Go additional_dependencies strings.
The secondary reason is that the scop/pre-commit-shfmt hook is in
actual, active use by the repo maintainer and others. As such it is more
likely to be kept up to date than `local` hooks which detach from
everything the moment they're added to local configs.
=> README: point pre-commit hook towards github.com/scop/pre-commit-shfmt

interp/api.go, interp/handler.go, interp/interp_test.go
=> interp: fix a PATH regression on Windows, fix tests on Wine

interp/builtin.go, interp/interp_test.go
Hi, thanks for this amazing package, I'm relying on it for cross platform build automation tasks.
And I came across the unexpected behavior of `cd -`, which errored when there is no directory named `-`, instead of chdir into last working directory.
In this pull request, the existence of directory named `-` in the current working directory is not checked as the man page says `cd -` is actually an alias of `cd ${OLDPWD}`, so to my understanding, a directory named `-` is ignored in this case (and I can confirm ash, zsh, bash on macos and linux all have this behavior).
=> builtin(cd): Support hyphen-minus operand

interp/interp_test.go, interp/runner.go
Change the operation to calculate the elapsed seconds from `Remainder` to `Mod`, as `Remainder` can return negative values.
Let me know if we need more test cases :)
Fixes #767
=> interp: fix negative elapsed time

interp/interp_test.go, syntax/lexer.go
the lexer assumes an extglob token if any of the wildcards expressions
(such as `@`, and `+`) are succeeded by a left parenthesis but that
proves to be an issue if the wildcard is used as a function name.
example input:
```
$ cat in.sh
@() {
echo "$@";
}
```
`bash` and `gosh` comparison:
```
$ bash ./in.sh
hello
$ ./gosh in.sh
in.sh:5:1: "}" can only be used to close a block
```
given `in.sh`, gosh reports about a syntax error - this is because
a closing bracket is found while the lexer isn't assuming a function
block
fix the issue by assuming a function if one of the conditions below is
true:
* if the expression is found at the beginning of the statement or if its
preceded by a "function"
* if `(` is immediately succeeded by a `)` - although this is a valid
bash syntax, we'll operate on …
=> lexer: allow extglob wildcards as function names

interp/interp_test.go
=> interp: re-enable process substitution tests on Mac

interp/builtin.go, interp/handler.go, interp/interp_test.go
`test -d ""` succeeds when it should fail. Checking all the flags which take a path in `gosh` (ignoring G and O which are not yet implemented):
```sh
for flag in b c d e f g h k L p r s S u w x; do
test -$flag ""
echo -n "$flag$? "
done
```
Results in `b1 c1 d0 e0 f1 g1 h1 k1 L1 p1 r0 s0 S1 u1 w1 x1`. Some are correctly failing, but for the wrong reasons.
`absPath` is updated to check for empty paths and return them untouched. `changeDir` was relying on the old behavior, so it now explicitly implements the same behavior as bash, dash, mksh, and zsh, where a `cd ''` is equivalent to a `cd .`. (This was also the previous behavior in gosh.)
Shell behavior was surveyed with:
```sh
try() {
local cmd="$1" want="$2"
for shell in bash csh dash gosh ksh mksh posh sh tcsh zsh; do
local got …
```
=> Check for empty paths in builtin test

syntax/filetests_test.go, syntax/lexer.go, syntax/printer.go, syntax/printer_test.go
=> syntax: support backquoted inline comments

syntax/filetests_test.go, syntax/lexer.go, syntax/parser_test.go, syntax/printer_test.go
=> syntax: support escaped newlines with CRLF

README.md
Trunk is a recently launched universal linter which integrates with a wide variety of linters and formatters, `shfmt` included.
We're big fans of `shfmt` and figured that you might find our tool to be interesting enough to include it here.
=> readme: document trunk

README.md
Adds the link to the existing list, which seems to be sorted alphabetical.  Trunk, the latest addition, seems to a paid software, too. 
If links to paid software are unwanted, please feel free to close.
BashSupport Pro is a paid plugin for JetBrains IDEs and bundles shfmt, but also support external installations.
=> Add BashSupport Pro as related project

cmd/shfmt/main.go, cmd/shfmt/shfmt.1.scd, cmd/shfmt/testdata/scripts/editorconfig.txt, cmd/shfmt/testdata/scripts/flags.txt, cmd/shfmt/testdata/scripts/walk.txt, fileutil/file.go
=> cmd/shfmt: change -ln default to "auto"

interp/interp_test.go, interp/vars.go
In dc2e11e `unset` of a global var inside a function was broken, as the special handling of `export` or `readonly` in function scope introduced in that commit also incorrectly captured `unset`, calling a parent.Set with the previous value.
Ensure we do not capture unset in the function scope global handling.
Unset of a global can fall-through this code. Globals are unset correctly further down the Set function, so we do not need to invoke a parent.Set at all.
Fixes mvdan#806
=> interp: fix unset global inside function

interp/api.go, interp/handler.go, interp/handler_test.go, interp/runner.go
I believe this is one of the last locations where the interpreter can bypass sandboxing, though there are a few explicit calls to `os.*` that remain.
As an aside related to #630,  it would be amazing if for v4 the interp package could be refactored to solely (or as close as possible) interact through the `fs.FS` interface. This would then allow the interpreter to be completely sandboxed. For example the existing [Runner.stat()](https://github.com/alecthomas/sh/blob/master/interp/runner.go#L901) function, and so on. This would also remove the need for `OpenHandler` and `ReadDirHandler`.
=> Add interp.ReadDirHandler for intercepting glob expansion.

.github/workflows/test.yml
update bash directly instead of use dockexec since got `no such file` error
close #785
=> interp: run "Confirm" tests on CI

README.md
I ran into some file permission and word splitting issues when using the -w flag in a directory with spaces in the name. I hope you find this pull request / documentation example useful.
=> Better docker run example

interp/api.go, interp/interp_test.go, interp/runner.go
=> interp: surface exit codes from command substitutions

expand/expand.go, interp/interp_test.go
=> expand: reimplement globstar globbing for correctness

syntax/printer.go, syntax/printer_test.go
=> syntax: strip escaped newlines from all non-quoted words

syntax/printer.go, syntax/printer_test.go
Also applies to sub-shell functions and command substitutions (including the deprecated legacy back-tick syntax).
Fixes #839.
=> Separate comment from sub-shell opening parenthesis with a space

interp/api.go, interp/builtin.go, interp/handler.go, interp/runner.go, interp/test.go
This feature allows intercepting the os.stat/os.Lstat operations in the interp to provide more flexible usage.
=> interp: use custom handler for os.stat/os.Lstat operations

interp/builtin.go, interp/interp_test.go
Add an initial implementation of mapfile or readarray, this version only
supports the basic options of `-d`, `-t`, and a custom array variable
name. At present it only support splitting on ASCII delimiters.
=> interp: add initial mapfile or readarray builtin

syntax/simplify.go, syntax/simplify_test.go
If the default for an unset-or-null parameter expansion is null, the or-null part of the expansion is redundant and can be removed. The result is null on match either way.
=> syntax: simplify unset-or-null with null default to just unset

cmd/shfmt/main.go
the `io.ReadAtLeast` at a minimum, checks for the shebang
directive but we're missing the `!`
=> shfmt: fix typo on FormatPath's

cmd/shfmt/main.go, cmd/shfmt/testdata/scripts/flags.txt
explicitly state language dialect on `syntax.LangError`s when ln
is set to `auto`
for example, incompatible bash constructs will cause parse errors
due to the parser using posix as language dialect
fixes #803
=> shfmt: state -ln=auto on posix parse errors

syntax/printer.go, syntax/printer_test.go
we want white space on nested subshells if its in a single line since
its ambiguous, eg we want `( (` over `((`
this shouldn't be the case for multiple lines- fix the logic that adds
white space to only do so if the two subshells are in the same line
fixes #814
=> syntax: fix whitespace on nested subshells

expand/expand.go, interp/interp_test.go
we currently don't support bash's `extglob` option and when attempted,
interp panics
fix expand so that we return the error properly and exit with status `1`
fixes #841
=> expand: do not panic on extglob nodes

syntax/parser.go, syntax/printer_test.go
=> syntax: parse a redirect edge case without spaces

expand/expand.go, interp/interp_test.go
=> expand: fix parameters with leading/trailing spaces

interp/api.go, interp/builtin.go, interp/interp_test.go, interp/test.go
Trying to set an unsupported but valid Bash option leads to a
potentially confusing error message:
```
$ gosh -c "shopt -s extglob"
shopt: invalid option name "extglob"
```
Fix that by handling the unsupported options differently from the
invalid ones:
```
$ gosh -c "shopt -s extglob"
bash: line 1: shopt: extglob off ("on" not supported)
exit status 1
```
Additionally, this commit lists all of the Bash options when `shopt`
without arguments is called and explicitly identify the unsupported
options, for example:
```
$ gosh -c "shopt"
expand_aliases  off
globstar        off
nullglob        off
// .. cut for brevity
hostcomplete    on      ("off" not supported)
inherit_errexit on      ("off" not supported)
interactive_comments    on      ("off" not supported)
```
While at it, rewrite the …
=> interp: display all Bash's `shopt` option

expand/expand.go, expand/param.go, interp/interp_test.go
=> expand: improve support for array keys and values

cmd/gosh/main_test.go, syntax/lexer.go
=> syntax: do not require peeking two bytes after `echo *`

interp/interp_test.go
Running the tests on master gives me the following error:
```
--- FAIL: TestRunnerRunConfirm (0.03s)
--- FAIL: TestRunnerRunConfirm/#420 (0.02s)
interp_test.go:3690: wrong bash output in "f() { echo 1; }; { sleep 0.01s; f; } & f() { echo 2; }; wait":
want: "1\n"
got:  "usage: sleep seconds\n1\n"
```
I am running on `bash version 5.1.16(1)-release`:
```
$ bash --version
GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.5.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
The error I suppose, is because of the difference of the sleep
syntax on BSD/Unix/MacOS vs on GNU/Linux - the …
=> interp_test: fix sleep syntax compatibility

syntax/printer.go, syntax/printer_test.go
=> syntax: allow escaped newlines to precede unquoted words again

interp/interp_test.go, syntax/parser_test.go
=> syntax: add a TODO reminder about C.UTF-8

cmd/shfmt/shfmt.1.scd
The shfmt manpage had a typo for the long-option `--case-indent`. It has
been corrected from `--switch-case-indent`, which was not a valid option.
Fixes #898.
=> cmd/shfmt: incorrect flag name for --case-indent

cmd/shfmt/json.go, cmd/shfmt/json_test.go, cmd/shfmt/main.go, cmd/shfmt/shfmt.1.scd, cmd/shfmt/testdata/json.json, cmd/shfmt/testdata/json.sh, cmd/shfmt/testdata/scripts/flags.txt, cmd/shfmt/testdata/scripts/tojson.txt, syntax/nodes.go
Fixes #35 again, as we never implemented the "read JSON" side.
=> cmd/shfmt: implement --from-json and improve -tojson

.github/workflows/test.yml
See: https://github.com/peter-evans/dockerhub-description/issues/10
Not mandatory but good to implement IMO:
1. create a Docker Hub token (needs read/write/delete rights)
2. replace DOCKER_PASSWORD with DOCKER_TOKEN in GH actions secrets.
3. eventually add 2FA authentication on Docker Hub (it was not possible because of that).
=> Use docker token

syntax/parser.go, syntax/parser_test.go
=> syntax: give a better error when "function" is used in posix mode

syntax/filetests_test.go, syntax/parser.go, syntax/parser_test.go
=> syntax: forbid ${!foo*} and ${!foo@} in mksh mode

expand/arith.go, interp/api.go, interp/handler.go, interp/handler_test.go, interp/interp_test.go, interp/runner.go
=> expand: avoid panics on division by zero

README.md
i wrote an extension for vscode that *only* formats shell script files and nothing else
=> add shfmt vscode extension

CHANGELOG.md, syntax/parser.go, syntax/printer.go, syntax/printer_test.go
Fixes #779.
Fixes #917.
cc @ainar-g @Julien-Elie @zx8 @DannyBen if you want to test this out
=> syntax: fix two bugs when formatting case clauses

interp/interp_test.go, interp/runner.go
interp already excludes conditional contexts for exiting on error when `errexit` is set (see case above); this makes the logic consistently apply the same filtering for reporting errors to a trap routine.
To test this behavior, I ran the below script under `bash`, under `gosh` (without this change), and under `gosh` (with this change). `bash` reports that the handler was invoked once. Without this change `gosh` reports that it was invoked twice, and with this change, only once.
```bash
#!/bin/bash
count=0
my_handler()
{
echo "Handler invoked"
count=$((count + 1))
}
trap my_handler ERR
echo "Trying unconditional"
non_existent_cmd
echo "Trying conditional"
non_existent_cmd || true
echo "Handler called: $count time(s)"
```
=> interp: make trap consistent with errexit logic

expand/expand.go, interp/interp_test.go
Update `printf` implementation to do the same as `echo -e` for the `%b` format specifier: expand backslash escape sequences in the provided argument but not `%` format specifiers.
Extracts inner logic from `Format` into `formatIntoBuffer` to avoid issues with non-reentrancy of `Format` (due to use of a special cached buffer in `Config`.
---
_Request for feedback_
This was the simplest change that I could see, but I wasn't thrilled about having `formatIntoBuffer` recursively call itself for the `%b` case; this shouldn't generally be problematic, since the recursive call won't process `%` format specifiers and shouldn't further recur.
=> interp: implement %b for printf builtin

CHANGELOG.md, interp/api.go, interp/interp_test.go
Set EUID variable analog to UID.
Signed-off-by: Jonathon Anderson <janderson@ciq.co>
=> interp: set EUID

syntax/typedjson/json.go
=> syntax/typedjson: avoid MethodByName

interp/api.go, interp/example_test.go, interp/handler_test.go, interp/interp_test.go
=> interp: add ExecHandlers to support exec middlewares

cmd/shfmt/shfmt.1.scd
The Google Shell Style Guide moved at some point, just updating the link.
=> Fix link to Google's Shell Style Guide

interp/builtin.go, interp/interp_test.go, interp/runner.go
the parser already supports the `select` command but the interpreter
treats it just like any other `for` command
given the syntax:
```
select name [in words ...]; do commands; done
```
fix support by:
* expanding and printing the words following `in`, to generate a list
of items, each preceeded by a number and a close parenthesis
* display the prompt and read the line from stdin
* assigning the selected option to a special variable in Bash called
`REPLY`
* support `PS3`, another special variable in Bash, which can be
set to the prompt while the shell awaits for input. if not provided,
defaults to `#?`:
additionally, `select` should loop until an input is provided. in case
of an invalid input, the name will be empty
```
$ bash -c 'PS3="pick one: "; select SEL in foo; do echo $REPLY; break; …
```
=> interp: handle select clause

interp/builtin.go
This fixes an issue where running `umask`, `fg` or `bg` causes a panic.
Related issue: https://github.com/diamondburned/libdb.so/issues/3
=> interp: umask/fg/bg shouldn't panic

interp/builtin.go, interp/interp_test.go, interp/runner.go
Some of the `errf` calls were missing new lines, so I added them. One call is left where new lines are not wanted.
=> interp: Fix (*Runner).errf missing new lines

cmd/shfmt/shfmt.1.scd
EditorConfig 0.15.0 does not allow inline comments
https://spec.editorconfig.org/#no-inline-comments
=> cmd/shfmt: remove inline EditorConfig comments

interp/builtin.go, interp/os_notunix.go, interp/os_unix.go
=> interp: fix `cd` builtin: call a system function to determine access instead of reverse-engineering it ourselves

cmd/shfmt/main.go, cmd/shfmt/shfmt.1.scd, cmd/shfmt/testdata/script/editorconfig.txtar
=> cmd/shfmt: add --apply-ignore flag for tools and editors

cmd/shfmt/shfmt.1.scd, cmd/shfmt/testdata/script/editorconfig.txtar
=> cmd/shfmt: document when --filename is needed for EditorConfig support

cmd/shfmt/shfmt.1.scd
=> cmd/shfmt: fix typo in shfmt.1.scd

expand/expand.go, expand/expand_test.go, interp/api.go, interp/interp_test.go, interp/runner.go, pattern/pattern.go
- Add a FoldCase flag to the expand.Config struct, which is used to configure how expand.Fields behaves.
- Similarly, add a FoldCase Mode to pattern.Regexp. Setting the flag adds (?i) to the front of the generated regular expression.
- Use the former to set the latter when calling expand.Fields.
- Use all of the above to implement the "nocaseglob" shopt.
Rationale: I use expand.Fields to do filename expansion, for which I'd like to do case-insensitive matching. E.g. I'd like "c*" to match both "cmd" and "CHANGELOG.md"
=> Allow case-insensitive filename globbing; add nocaseglob

syntax/walk.go
In DebugPrint, if a value implements fmt.Stringer, and isn't a zero value, display its string value in addition to the default %#v format.
For the most part, this prints the string value of "tokens", e.g. for a syntax.Redirect.Op, instead of "Op: 0x3b", you get "Op: 0x3b (>&)".
=> DebugPrint: Print the string value of tokens

interp/os_notunix.go, interp/os_unix.go, interp/test.go
Implement -O (syntax.TsUsrOwn, "file exists and is owned by the effective user id") and -G (syntax.TsGrpOwn, "file exists and is owned by the effective group id") tests, for non-Windows only.
Under Windows, still panics, as before.
-O and -G are hard/not applicable for Windows, since it doesn't really have the concept of "file owners", only ACLs, and it's not clear how to translate one to the other.
=> Implement -O and -G tests

interp/builtin.go
This implements the -s option for the read builtin using the ReadPassword function in the golang.org/x/term package. This is a less featureful (and as a result, simpler) implementation of the -s flag than is present in https://github.com/mvdan/sh/pull/865
Like PR865, I am also unsure of how to test the -s flag since it requires interacting with the terminal input.
=> interp: add -s support for read builtin

.github/workflows/test.yml, expand/expand.go, expand/expand_nonwindows.go, expand/expand_windows.go, interp/handler.go, interp/os_notunix.go, interp/os_unix.go
=> fix and test builds for GOOS=plan9

pattern/pattern.go
TranslatePattern and QuotePattern were renamed Regexp and QuoteMeta
in 2019 when code was moved out "syntax" package to "pattern" one.
See 2e72e3c7a085f23431db3c6cfb01da390fd5003c
=> pattern: fix outdated comment, and add godoc links

interp/builtin.go
this is a zero code changes. The signature was already the right one.
We are just using an alias, that will make things clearer.
=> interp: improve method signature

README.md
Adds [neoformat](https://github.com/sbdchd/neoformat) to the list of related projects.
=> README: Add neoformat NeoVim / Vim plugin

cmd/shfmt/main.go, cmd/shfmt/shfmt.1.scd, cmd/shfmt/testdata/script/editorconfig.txtar
I've never used `go` before, so I this is a naive, but working approach to support `simplify` and `minify` in editorconfig files. I have not looked at adding tests yet, but will add tests if this code change approach is agreeable.
Manual testing below.
```bash
$ for opt in "" "simplify=true" "minify=true"; do echo $'[[shell]]\nindent=4\n'"$opt" > .editorconfig; echo "### $opt"; shfmt --diff f.sh; done
###
--- f.sh.orig
+++ f.sh
@@ -1,11 +1,11 @@
#!/bin/bash
ff() {
-local h=asdffdfd
+       local h=asdffdfd
}
g=a
-echo $(( 1 + 2 ));
+echo $((1 + 2))
ff
echo $h
[[ "$HOME" == "$HELLO" ]]
--- f.sh.orig
+++ f.sh
@@ -1,11 +1,11 @@
#!/bin/bash
ff() {
-local h=asdffdfd
+       local h=asdffdfd
}
g=a
-echo $(( 1 + 2 ));
+echo $((1 + 2))
ff
echo $h
-[[ "$HOME" == "$HELLO" ]]
+[[ $HOME == "$HELLO" …
```
=> cmd/shfmt: Add support for minify and simplify via EditorConfig

interp/interp_test.go, syntax/parser_test.go
Revert "all: assume C.UTF-8 is available in the tests"
This reverts commit dfc1441b9cd87d9430893024743aa2197a8e3e8f.
---
That commits assumes `C.UTF-8` is available everywhere, but it is not really available on macOS, making several tests fail because this is prefixed on the expected outputs:
```
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): Bad file descriptor
```
Also, FYI `TestRunnerRunConfirm` is still failing on macOS after this change. I may take a look soon.
```
ok  	mvdan.cc/sh/v3/cmd/gosh	(cached)
ok  	mvdan.cc/sh/v3/cmd/shfmt	(cached)
ok  	mvdan.cc/sh/v3/expand	(cached)
ok  	mvdan.cc/sh/v3/fileutil	(cached)
--- FAIL: TestRunnerRunConfirm (0.02s)
--- FAIL: TestRunnerRunConfirm/#433 (0.01s)
interp_test.go:4012: wrong bash output in "echo foo >&- 2>&-; :":
want: …
```
=> Revert `C.UTF-8` on tests to fix tests on macOS

interp/interp_test.go, interp/runner.go
We were getting the following error on a given script:
declare: invalid option "-Ag"
=> fix(interp): allow multiple options on `declare` (`-Ag`)

expand/expand.go
This is a followup to #1147 and #1149 to slightly simplify the logic and add some tests.
After adding `pattern.NoGlobStar` in #1147 I had a nagging doubt that I should have addded some code to use this new mode in the expand package, depending on whether `cfg.GlobStar` was enabled or not. I spent some time this afternoon checking that assumption, and I can't find a way to get the expand package to use the GlobStar support in the pattern package, even before the fixes you added for #1149 where the behavior was different.
But it's possible I missed something, and I think it's a good idea to disable the unused functionality just in case. Hence this PR.
=> expand: always use pattern.NoGlobStar option

README.md
```sh
$ echo '${array[weird!key]}' | shfmt
<standard input>:1:8: reached ! without matching [ with ]
```
I was not aware of this limitation but saw it in README just before filing a bug. Let's add another example, mostly for the sake of discoverability.
While at it, add <standard input> to an existing example, as this is how the output looks like now (using v3.11).
=> README.md: add another example to caveats

cmd/shfmt/shfmt.1.scd
"to set any option" reads kind of vague to me.
The option equivalent to shell_variant is `--language-dialect`, not `--language-variant`.
`simplify` and `minify` were missing.
=> cmd/shfmt: rephrase and update manual's editorconfig options

.github/workflows/test.yml, interp/builtin.go, interp/interp_test.go
Right now it merely exits 1, which IMHO lacks context.
=> fix: output error when changing into a dir that doesn't exist
