- interp/interp.go
- interp/interp_test.go
Ref #86
I'm not familiar with the code base, so feel free to close if it's not the right way to do it.
> interp: Add support for Context

- cmd/gosh/main.go
```bash
gosh -c "echo 'Hello, World'"
```
> gosh: allow -c flag

- README.md
Hi, I hope vim users find this useful.
> README: add vim-shfmt to related projects

- fileutil/file.go
Addresses #152
I can try adding a test this weekend if you want.
> Don't test symlinks to directories

- interp/interp.go
- interp/module.go
- interp/module_test.go
The code as is works. But I don't know do you would prefer to add this. Should it always send Interrupt or have an options to choose how to handle it? For an option: what would be the default?
> interp: send Interrupt to processes instead of Kill when possible

- interp/expand.go
- interp/interp_test.go
Prior art:
2f57c11bc23b930b055fe5d20aa784777acaf2b9,
90adc2485eb90195d32fc48951d51dba10055661, #175
Fixes #269
> interp: Handle \" inside "

- README.md
Modd is a flexible developer tool that runs processes and responds to filesystem changes, which embeds sh as its built-in shell.
Many thanks for sh - embedding a shell in modd has made the cross-platform story for the tool much nicer.
> Add modd to README.md

- interp/example_test.go
- interp/handler.go
- interp/handler_test.go
- interp/interp.go
- interp/interp_test.go
> interp: rename Exec/OpenModule to Exec/OpenHandler

- README.md
I've made a wrapper plugin of `shfmt` for Sublime Text 3.
This request adds link to the plugin repository in `README.md`.
Making an issue for this wouldn't make sense so I chose this way (PR).
> README: update Related projects

- cmd/shfmt/Dockerfile
> cmd/shfmt: build with latest git tag as version

- README.md
Hi there
I've been used the shfmt for a longe time, and since the beginning of this year, I started to validate my projects using github actions. 
This PR adds a link to the project in README.md. I checked and there is no other github action do to that. Btw, I reorder the links by name.
> update related projects

- _js/main.go
- _js/testmain.js
I'm a new bee to Golang, but hoping to help to resolve #523.
> feat: sync js package with main go module

- README.md
I wrote an Emacs package to integrate `shfmt`, which may interest some of your users. Thanks!
> Link to Emacs shfmt package

- README.md
- cmd/shfmt/main.go
- cmd/shfmt/testdata/scripts/editorconfig.txt
Untested, but at least communicates the idea if it doesn't work :)
> cmd/shfmt: use function_next_line from editorconfig

- interp/interp_test.go
- interp/runner.go
- syntax/nodes.go
Fix #597 
- Comment about nil for loop components
- Add tests
- Check for nil in loop runner
Feel free to make edits, this is my first PR here, thanks.
> interp: For loop with missing components fix

- README.md
Include mention to intellij jetbrain bundled plugin invoking shfmt
> Update README.md with intellij support

- interp/api.go
- interp/builtin.go
- interp/interp_test.go
- interp/runner.go
> interp: implement trap of ERR and EXIT signals

- syntax/parser_test.go
> syntax: stop ignoring shell parse warnings in tests

- interp/interp_test.go
- interp/os_unix.go
- syntax/parser_test.go
> all: make tests pass on the debian-minimal docker image

- interp/builtin.go
- interp/interp_test.go
> interp: make "cd -" print the new directory

- cmd/shfmt/main.go
- cmd/shfmt/testdata/scripts/walk.txt
> cmd/shfmt: don't duplicate errors when walking dirs

- syntax/filetests_test.go
- syntax/lexer.go
- syntax/parser.go
- syntax/parser_test.go
> syntax: add support for heredocs directly inside backquotes

- go.mod
- syntax/filetests_test.go
- syntax/parser.go
- syntax/parser_test.go
> syntax: improve table-driven test machinery

- interp/interp_test.go
the interp_test's `touch` does not support the `-t` flag, instead it
treats it as filenames to be created
to fix, remove the `-d` support in favor of `-t` as part of the
compatibility fixes introduced in d36d14903235de79f41ca3bea388f83ce33ad174
if the `-t` flag is detected, parse the next argument to time.Time
as timestamp to the files (the rest of the argument) that will be created
fixes #784
> interp_test: fix broken touch implementation

- interp/api.go
- interp/handler.go
- interp/handler_test.go
- interp/runner.go
> interp: add CallHandler

- syntax/nodes.go
- syntax/parser.go
> syntax: add NewPos

- cmd/shfmt/main.go
- cmd/shfmt/shfmt.1.scd
- cmd/shfmt/testdata/scripts/flags.txt
- cmd/shfmt/testdata/scripts/walk.txt
- syntax/parser.go
Updates #802.
Fixes #802.
cc @kolyshkin
> follow-up fixes for -ln=auto

- interp/handler.go
- interp/runner.go
- shell/expand.go
- syntax/nodes.go
- syntax/parser.go
- syntax/printer.go
> all: fix a few typos spotted by gospel

- README.md
> README: shfmt is now in Debian as well

- interp/api.go
- interp/builtin.go
- interp/interp_test.go
> interp: panic on set builtin with the end of options flag

- expand/expand.go
- interp/interp_test.go
> expand: replace os.Stat with cfg.ReadDir

- .github/workflows/test.yml
- go.mod
> drop Go 1.16, add 1.18, add CI checks

- README.md
- interp/interp_test.go
This will avoid the path collision seen in https://github.com/mvdan/sh/issues/738.
Fixes https://github.com/mvdan/sh/issues/738.
> Replace foo/bar with longer names

- fileutil/file.go
- syntax/printer.go
- syntax/printer_test.go
> syntax: write shebang in minify mode

- cmd/shfmt/Dockerfile
- cmd/shfmt/main.go
- cmd/shfmt/shfmt.1.scd
- cmd/shfmt/testdata/scripts/basic.txt
- cmd/shfmt/testdata/scripts/diff.txt
- cmd/shfmt/testdata/scripts/flags.txt
- cmd/shfmt/testdata/scripts/simplify.txt
- cmd/shfmt/testdata/scripts/walk.txt
> cmd/shfmt: support long flags

- CHANGELOG.md
> CHANGELOG: prepare for v3.5.0

- README.md
> README: clarify docker image tags

- shell/doc.go
- syntax/lexer.go
- syntax/parser.go
- syntax/parser_arithm.go
- syntax/simplify.go
Plus some other related changes.
> syntax: tone down the parser's use of batch allocations

- syntax/lexer.go
- syntax/parser.go
- syntax/parser_test.go
> syntax: add error message for herestrings in POSIX mode

- syntax/typedjson/json.go
> syntax/typedjson: avoid using reflect.VisibleFields

- syntax/lexer.go
- syntax/parser.go
> syntax: appease unconvert

- interp/interp_test.go
- interp/trace.go
when enabled trace should send its output to stderr
fixes  mvdan/sh#926
> resolves trace issue

- expand/arith.go
- interp/builtin.go
- interp/interp_test.go
> expand,interp: trim whitespace in atoi

- CHANGELOG.md
- README.md
> CHANGELOG: draft for v3.6.0

- syntax/parser.go
- syntax/testdata/fuzz/FuzzParsePrint/293db3718a4ab7a5
> syntax: fix a parser crash when trying to produce a friendly error

- cmd/shfmt/testdata/script/walk.txtar
> cmd/shfmt: test that we treat symlinks right when walking

- interp/builtin.go
- interp/handler_test.go
- interp/interp_test.go
- interp/unexported_test.go
- interp/unix_test.go
- interp/windows_test.go
> interp: make tests external and improve wording

- cmd/gosh/main.go
- cmd/shfmt/main.go
- expand/arith.go
- expand/braces.go
- expand/environ.go
- expand/expand.go
- fileutil/file.go
- interp/api.go
- interp/builtin.go
- interp/handler.go
- interp/interp_test.go
- pattern/pattern.go
- syntax/nodes.go
- syntax/parser.go
- syntax/typedjson/json.go
> all: start using doc links

- syntax/simplify.go
- syntax/simplify_test.go
> Revert "syntax: simplify unset-or-null with null default to just unset"

- interp/interp_test.go
- interp/runner.go
> interp: support combining pipefail and errexit

- expand/expand.go
> expand: tidy up ReadFields godoc TODO

- .github/workflows/test.yml
- README.md
- cmd/shfmt/Dockerfile
- go.mod
> all: add Go 1.21, drop 1.19

- syntax/printer.go
- syntax/printer_test.go
> syntax: Allow redirects before all arguments

- cmd/shfmt/shfmt.1.scd
> cmd/shfmt: document how EditorConfig's "ignore" works

- README.md
- Wanted to add an entry for my own tool that uses `shfmt` under the hood.
> Add dockerfmt tool

- expand/expand.go
- interp/interp_test.go
- Follow-up of #841
- Follow-up of #875
There was a missing place that could also panic.
> fix(interp): do not panic on extglob
